image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make puredata-dev
  script: 
    - make
  dependencies: []
  artifacts:
    paths:
      - "*.pd_linux"
    expire_in: 1 week
