image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make puredata-dev
  script: 
    - declare -x CI_BUILD_REF_SHORT=$(git describe --tags)
    - export
    - make
    - make install DESTDIR=$(pwd) pkglibdir=
  dependencies: []
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_BUILD_REF_SHORT}
    paths:
      - iemguts/
      - examples/
    expire_in: 1 week
