image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make puredata-dev
  script: 
    - make
    - make install DESTDIR=$(pwd) pkglibdir=/
  dependencies: []
  artifacts:
    name: iemguts-snapshot
    paths:
      - iemguts/
    expire_in: 1 week
