image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make puredata-dev
  script: 
    - export
    - make
    - make install DESTDIR=$(pwd) pkglibdir=
  dependencies: []
  artifacts:
    paths:
      - iemguts/
      - examples/
    expire_in: 1 week
